# Generated by Django 5.0 on 2023-12-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0001_initial'),
        ('posts_app', '0002_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
